CREATE TABLE action_spec (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    space_id BIGINT NOT NULL,
    action_code VARCHAR(128) NOT NULL,
    connector_id BIGINT NOT NULL,
    operation_binding_json JSON,
    allowed_auth_profiles_json JSON,
    default_auth_profile_code VARCHAR(64),
    binding_strategies_json JSON,
    input_schema_json JSON,
    output_schema_json JSON,
    idempotency_policy_json JSON,
    risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW',
    approval_policy_id BIGINT,
    side_effect_level VARCHAR(32) NOT NULL DEFAULT 'write',
    observability_profile_json JSON,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    version INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_space_action_version (space_id, action_code, version),
    KEY idx_action_space_status (space_id, status, id)
);

CREATE TABLE interaction_spec (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    space_id BIGINT NOT NULL,
    interaction_code VARCHAR(128) NOT NULL,
    slot_schema_json JSON,
    ask_strategy_json JSON,
    auto_fill_rules_json JSON,
    summary_layout_json JSON,
    confirmation_policy_json JSON,
    edit_policy_json JSON,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    version INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_space_interaction_version (space_id, interaction_code, version),
    KEY idx_interaction_space_status (space_id, status, id)
);
