CREATE TABLE workflow_spec (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    space_id BIGINT NOT NULL,
    workflow_code VARCHAR(128) NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    interaction_spec_id BIGINT,
    risk_aggregation_policy VARCHAR(64) NOT NULL DEFAULT 'max_step_risk',
    approval_aggregation_policy VARCHAR(64) NOT NULL DEFAULT 'strictest_step_policy',
    failure_policy_json JSON,
    audit_policy_json JSON,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    version INT NOT NULL DEFAULT 1,
    published_artifact_ref VARCHAR(256),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_space_workflow_version (space_id, workflow_code, version),
    KEY idx_workflow_space_status (space_id, status, id)
);

CREATE TABLE workflow_step (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    workflow_id BIGINT NOT NULL,
    step_id VARCHAR(128) NOT NULL,
    step_name VARCHAR(256) NOT NULL,
    step_type VARCHAR(32) NOT NULL,
    connector_id BIGINT,
    target_ref VARCHAR(128),
    allowed_auth_profiles_json JSON,
    binding_strategies_json JSON,
    input_mapping_json JSON,
    output_mapping_json JSON,
    depends_on_json JSON,
    condition_json JSON,
    join_policy_json JSON,
    retry_policy_json JSON,
    timeout_policy_json JSON,
    approval_gate_json JSON,
    compensation_target_ref VARCHAR(128),
    resume_policy_json JSON,
    step_order INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'enabled',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_workflow_step (workflow_id, step_id),
    KEY idx_workflow_step_order (workflow_id, step_order)
);
