-- 注册查询型 resolver 工具。
-- 这些工具只用于槽位补全与依赖解析，不出现在用户可调用工具目录中。

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES
(
    'default',
    'gougu_oa.leave_type_options',
    '请假类型选项',
    '查询勾股 OA 请假类型候选项。',
    'gougu_oa',
    '/api/oa_integration/get_leave_types',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["fetch"],"terminal":["fetch"],"steps":{"fetch":{"stepId":"fetch","name":"获取请假类型","type":"HTTP","config":{"method":"GET","endpoint":"/api/oa_integration/get_leave_types","contentType":"application/json","outputMapping":{"data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.approver_candidates',
    '审批人候选项',
    '查询直属上级优先的审批人候选项，同时返回完整员工列表。',
    'gougu_oa',
    '/api/oa_integration/get_department_users_tree',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["fetch"],"terminal":["fetch"],"steps":{"fetch":{"stepId":"fetch","name":"获取审批人候选项","type":"HTTP","config":{"method":"GET","endpoint":"/api/oa_integration/get_department_users_tree","contentType":"application/json","outputMapping":{"data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.user_directory',
    '员工目录选项',
    '查询全量员工目录候选项。',
    'gougu_oa',
    '/api/oa_integration/get_all_users',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["fetch"],"terminal":["fetch"],"steps":{"fetch":{"stepId":"fetch","name":"获取员工目录","type":"HTTP","config":{"method":"GET","endpoint":"/api/oa_integration/get_all_users","contentType":"application/json","outputMapping":{"data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.leave_flow_options',
    '请假审批流选项',
    '查询请假场景可用审批流。',
    'gougu_oa',
    '/api/check/get_flow_nodes?flow_id=0&action_id=0&check_name=leaves',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["fetch"],"terminal":["fetch"],"steps":{"fetch":{"stepId":"fetch","name":"获取请假审批流","type":"HTTP","config":{"method":"GET","endpoint":"/api/check/get_flow_nodes?flow_id=0&action_id=0&check_name=leaves","contentType":"application/json","outputMapping":{"data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.meeting_room_options',
    '会议室选项',
    '查询会议室候选项。',
    'gougu_oa',
    '/api/oa_integration/get_meeting_rooms',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["fetch"],"terminal":["fetch"],"steps":{"fetch":{"stepId":"fetch","name":"获取会议室候选项","type":"HTTP","config":{"method":"GET","endpoint":"/api/oa_integration/get_meeting_rooms","contentType":"application/json","outputMapping":{"data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.meeting_requirement_options',
    '会议需求选项',
    '查询会议需求候选项。',
    'gougu_oa',
    '/api/oa_integration/get_meeting_requirements',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["fetch"],"terminal":["fetch"],"steps":{"fetch":{"stepId":"fetch","name":"获取会议需求候选项","type":"HTTP","config":{"method":"GET","endpoint":"/api/oa_integration/get_meeting_requirements","contentType":"application/json","outputMapping":{"data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.meeting_flow_options',
    '会议审批流选项',
    '查询会议室预定场景可用审批流。',
    'gougu_oa',
    '/api/check/get_flow_nodes?flow_id=0&action_id=0&check_name=meeting_order',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["fetch"],"terminal":["fetch"],"steps":{"fetch":{"stepId":"fetch","name":"获取会议审批流","type":"HTTP","config":{"method":"GET","endpoint":"/api/check/get_flow_nodes?flow_id=0&action_id=0&check_name=meeting_order","contentType":"application/json","outputMapping":{"data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
