ALTER TABLE tool_meta
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '租户标识',
    MODIFY COLUMN tool_code VARCHAR(128) NOT NULL COMMENT '工具编码',
    MODIFY COLUMN tool_name VARCHAR(256) NOT NULL COMMENT '工具名称',
    MODIFY COLUMN description TEXT COMMENT '工具描述',
    MODIFY COLUMN system_code VARCHAR(64) NOT NULL COMMENT '所属系统编码',
    MODIFY COLUMN api_endpoint VARCHAR(512) COMMENT '默认接口地址',
    MODIFY COLUMN http_method VARCHAR(16) COMMENT '默认请求方法',
    MODIFY COLUMN content_type VARCHAR(128) COMMENT '默认内容类型',
    MODIFY COLUMN parameter_schema TEXT COMMENT '输入参数结构定义',
    MODIFY COLUMN execution_plan TEXT COMMENT '执行计划定义',
    MODIFY COLUMN interaction_policy TEXT COMMENT '交互策略定义',
    MODIFY COLUMN risk_level VARCHAR(16) NOT NULL DEFAULT 'LOW' COMMENT '风险等级',
    MODIFY COLUMN requires_auth TINYINT NOT NULL DEFAULT 1 COMMENT '是否需要身份认证',
    MODIFY COLUMN requires_confirm TINYINT NOT NULL DEFAULT 0 COMMENT '是否需要用户确认',
    MODIFY COLUMN capability_type VARCHAR(16) NOT NULL DEFAULT 'ACTION' COMMENT '工具能力类型',
    MODIFY COLUMN version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'enabled' COMMENT '启用状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE identity_binding
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN assistant_uid VARCHAR(128) NOT NULL COMMENT '平台用户标识',
    MODIFY COLUMN system_code VARCHAR(64) NOT NULL COMMENT '企业系统编码',
    MODIFY COLUMN system_user_id VARCHAR(128) NOT NULL COMMENT '企业系统用户标识',
    MODIFY COLUMN auth_type VARCHAR(32) NOT NULL DEFAULT 'TOKEN' COMMENT '绑定凭证类型',
    MODIFY COLUMN credentials TEXT COMMENT '绑定凭证内容',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '绑定状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE token_lease
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN lease_id VARCHAR(64) NOT NULL COMMENT '租约标识',
    MODIFY COLUMN access_token TEXT NOT NULL COMMENT '访问令牌',
    MODIFY COLUMN system_code VARCHAR(64) NOT NULL COMMENT '企业系统编码',
    MODIFY COLUMN assistant_uid VARCHAR(128) NOT NULL COMMENT '平台用户标识',
    MODIFY COLUMN expires_at DATETIME NOT NULL COMMENT '过期时间',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '租约状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE audit_event
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL COMMENT '事件唯一标识',
    MODIFY COLUMN trace_id VARCHAR(64) NOT NULL COMMENT '链路追踪标识',
    MODIFY COLUMN execution_id VARCHAR(64) COMMENT '执行标识',
    MODIFY COLUMN run_id VARCHAR(128) NULL COMMENT '运行标识',
    MODIFY COLUMN step_id VARCHAR(128) NULL COMMENT '步骤标识',
    MODIFY COLUMN event_type VARCHAR(64) NULL COMMENT '事件类型',
    MODIFY COLUMN thread_id VARCHAR(64) COMMENT '会话线程标识',
    MODIFY COLUMN assistant_uid VARCHAR(128) COMMENT '平台用户标识',
    MODIFY COLUMN system_code VARCHAR(64) COMMENT '企业系统编码',
    MODIFY COLUMN tool_name VARCHAR(128) COMMENT '工具编码',
    MODIFY COLUMN agent_phase VARCHAR(16) COMMENT '运行阶段',
    MODIFY COLUMN tool_input TEXT COMMENT '工具输入快照',
    MODIFY COLUMN tool_output TEXT COMMENT '工具输出快照',
    MODIFY COLUMN duration_ms BIGINT COMMENT '执行耗时毫秒',
    MODIFY COLUMN status VARCHAR(16) NOT NULL COMMENT '事件状态',
    MODIFY COLUMN error_message TEXT COMMENT '错误信息',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE checkpoint
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN thread_id VARCHAR(128) NOT NULL COMMENT '线程标识',
    MODIFY COLUMN checkpoint_id VARCHAR(128) NOT NULL COMMENT '检查点标识',
    MODIFY COLUMN state_json LONGTEXT NOT NULL COMMENT '状态快照',
    MODIFY COLUMN parent_id VARCHAR(128) COMMENT '父检查点标识',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE system_access_profile
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN system_code VARCHAR(64) NOT NULL COMMENT '企业系统编码',
    MODIFY COLUMN base_url VARCHAR(512) NOT NULL COMMENT '系统基础地址',
    MODIFY COLUMN token_endpoint VARCHAR(512) COMMENT '令牌接口地址',
    MODIFY COLUMN token_method VARCHAR(16) DEFAULT 'POST' COMMENT '令牌接口方法',
    MODIFY COLUMN token_request_tpl TEXT COMMENT '令牌请求模板',
    MODIFY COLUMN token_response_path VARCHAR(256) DEFAULT 'data.token' COMMENT '令牌响应提取路径',
    MODIFY COLUMN token_header_name VARCHAR(64) DEFAULT 'Authorization' COMMENT '令牌请求头名称',
    MODIFY COLUMN token_header_prefix VARCHAR(64) DEFAULT 'Bearer ' COMMENT '令牌请求头前缀',
    MODIFY COLUMN token_ttl_seconds INT DEFAULT 7200 COMMENT '令牌有效期秒数',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'enabled' COMMENT '配置状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE local_user_account
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN username VARCHAR(128) NOT NULL COMMENT '登录用户名',
    MODIFY COLUMN password_hash VARCHAR(128) NOT NULL COMMENT '密码摘要',
    MODIFY COLUMN display_name VARCHAR(128) COMMENT '显示名称',
    MODIFY COLUMN tenant_id BIGINT COMMENT '租户标识',
    MODIFY COLUMN system_code VARCHAR(64) NOT NULL DEFAULT 'gougu_oa' COMMENT '默认系统编码',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '账号状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE platform_space
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN space_code VARCHAR(64) NOT NULL COMMENT '空间编码',
    MODIFY COLUMN space_name VARCHAR(128) NOT NULL COMMENT '空间名称',
    MODIFY COLUMN environment VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境标识',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '空间状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE connector
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN space_id BIGINT NOT NULL COMMENT '所属空间标识',
    MODIFY COLUMN connector_code VARCHAR(64) NOT NULL COMMENT '连接器编码',
    MODIFY COLUMN system_code VARCHAR(64) DEFAULT NULL COMMENT '企业系统编码',
    MODIFY COLUMN display_name VARCHAR(128) NOT NULL COMMENT '显示名称',
    MODIFY COLUMN protocol_type VARCHAR(32) NOT NULL COMMENT '协议类型',
    MODIFY COLUMN environment VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '运行环境',
    MODIFY COLUMN network_zone VARCHAR(32) NOT NULL DEFAULT 'intranet' COMMENT '网络区域',
    MODIFY COLUMN base_url VARCHAR(512) NOT NULL COMMENT '基础地址',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'draft' COMMENT '连接器状态',
    MODIFY COLUMN version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE auth_profile
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN space_id BIGINT NOT NULL COMMENT '所属空间标识',
    MODIFY COLUMN connector_id BIGINT NOT NULL COMMENT '所属连接器标识',
    MODIFY COLUMN auth_profile_code VARCHAR(64) NOT NULL COMMENT '认证配置编码',
    MODIFY COLUMN auth_type VARCHAR(32) NOT NULL COMMENT '认证类型',
    MODIFY COLUMN usage_policy VARCHAR(32) NOT NULL DEFAULT 'read_only' COMMENT '使用策略',
    MODIFY COLUMN token_endpoint VARCHAR(512) COMMENT '认证接口地址',
    MODIFY COLUMN token_header_name VARCHAR(64) DEFAULT 'Authorization' COMMENT '认证请求头名称',
    MODIFY COLUMN token_header_prefix VARCHAR(64) DEFAULT 'Bearer ' COMMENT '认证请求头前缀',
    MODIFY COLUMN audience VARCHAR(256) COMMENT '目标受众',
    MODIFY COLUMN scopes_json JSON COMMENT '作用域集合',
    MODIFY COLUMN credential_ref VARCHAR(256) COMMENT '凭证引用',
    MODIFY COLUMN refresh_policy_json JSON COMMENT '刷新策略',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'draft' COMMENT '认证配置状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE principal_binding
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN space_id BIGINT NOT NULL COMMENT '所属空间标识',
    MODIFY COLUMN connector_id BIGINT NOT NULL COMMENT '所属连接器标识',
    MODIFY COLUMN platform_principal_id VARCHAR(128) NOT NULL COMMENT '平台主体标识',
    MODIFY COLUMN platform_principal_type VARCHAR(32) NOT NULL DEFAULT 'user' COMMENT '平台主体类型',
    MODIFY COLUMN target_principal_type VARCHAR(32) NOT NULL COMMENT '目标主体类型',
    MODIFY COLUMN target_principal_id VARCHAR(128) NOT NULL COMMENT '目标主体标识',
    MODIFY COLUMN scope_constraints_json JSON COMMENT '作用域约束',
    MODIFY COLUMN priority INT NOT NULL DEFAULT 100 COMMENT '优先级',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '绑定状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE agent_app
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN space_id BIGINT NOT NULL COMMENT '所属空间标识',
    MODIFY COLUMN agent_app_code VARCHAR(128) NOT NULL COMMENT '应用编码',
    MODIFY COLUMN display_name VARCHAR(256) NOT NULL COMMENT '应用名称',
    MODIFY COLUMN prompt_policy_json JSON COMMENT '提示词策略',
    MODIFY COLUMN memory_policy_json JSON COMMENT '记忆策略',
    MODIFY COLUMN approval_strategy_json JSON COMMENT '审批策略',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'draft' COMMENT '应用状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE agent_app_grant
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN agent_app_id BIGINT NOT NULL COMMENT '智能体应用标识',
    MODIFY COLUMN target_type VARCHAR(32) NOT NULL COMMENT '授权目标类型',
    MODIFY COLUMN target_code VARCHAR(128) NOT NULL COMMENT '授权目标编码',
    MODIFY COLUMN grant_mode VARCHAR(16) NOT NULL DEFAULT 'allow' COMMENT '授权模式',
    MODIFY COLUMN constraints_json JSON COMMENT '授权约束',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE local_user_grant
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN local_user_id BIGINT NOT NULL COMMENT '本地用户标识',
    MODIFY COLUMN grant_type VARCHAR(32) NOT NULL COMMENT '授权类型',
    MODIFY COLUMN grant_code VARCHAR(128) NOT NULL COMMENT '授权编码',
    MODIFY COLUMN scope_type VARCHAR(32) NOT NULL DEFAULT 'global' COMMENT '作用域类型',
    MODIFY COLUMN scope_code VARCHAR(255) NOT NULL DEFAULT '*' COMMENT '作用域编码',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '授权状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE execution_run
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN run_id VARCHAR(128) NOT NULL COMMENT '运行标识',
    MODIFY COLUMN artifact_code VARCHAR(128) NOT NULL COMMENT '工具编码',
    MODIFY COLUMN artifact_type VARCHAR(32) NOT NULL COMMENT '工具类型',
    MODIFY COLUMN space_id BIGINT NOT NULL COMMENT '所属空间标识',
    MODIFY COLUMN platform_principal_id VARCHAR(128) COMMENT '平台用户标识',
    MODIFY COLUMN thread_id VARCHAR(128) COMMENT '线程标识',
    MODIFY COLUMN context_snapshot_json JSON NULL COMMENT '运行上下文快照',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '运行状态',
    MODIFY COLUMN paused_step_id VARCHAR(128) NULL COMMENT '暂停步骤标识',
    MODIFY COLUMN approval_request_id VARCHAR(128) NULL COMMENT '关联审批请求标识',
    MODIFY COLUMN started_at DATETIME COMMENT '开始时间',
    MODIFY COLUMN completed_at DATETIME COMMENT '完成时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE execution_step
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN run_id VARCHAR(128) NOT NULL COMMENT '运行标识',
    MODIFY COLUMN step_id VARCHAR(128) NOT NULL COMMENT '步骤标识',
    MODIFY COLUMN step_name VARCHAR(256) COMMENT '步骤名称',
    MODIFY COLUMN connector_id BIGINT COMMENT '连接器标识',
    MODIFY COLUMN auth_profile_code VARCHAR(128) COMMENT '认证配置编码',
    MODIFY COLUMN principal_binding_id BIGINT COMMENT '主体绑定标识',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '步骤状态',
    MODIFY COLUMN started_at DATETIME COMMENT '开始时间',
    MODIFY COLUMN completed_at DATETIME COMMENT '完成时间',
    MODIFY COLUMN error_message TEXT COMMENT '错误信息',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE approval_request
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN request_id VARCHAR(128) NOT NULL COMMENT '审批请求标识',
    MODIFY COLUMN run_id VARCHAR(128) NOT NULL COMMENT '运行标识',
    MODIFY COLUMN step_id VARCHAR(128) NOT NULL COMMENT '步骤标识',
    MODIFY COLUMN approval_channel VARCHAR(64) COMMENT '审批渠道',
    MODIFY COLUMN approver_principal_id VARCHAR(128) COMMENT '审批人主体标识',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '审批状态',
    MODIFY COLUMN requested_at DATETIME COMMENT '发起时间',
    MODIFY COLUMN responded_at DATETIME COMMENT '响应时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE agent_task
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN task_id VARCHAR(128) NOT NULL COMMENT '任务标识',
    MODIFY COLUMN thread_id VARCHAR(128) NULL COMMENT '线程标识',
    MODIFY COLUMN assistant_uid VARCHAR(128) NULL COMMENT '平台用户标识',
    MODIFY COLUMN run_id VARCHAR(128) NULL COMMENT '运行标识',
    MODIFY COLUMN task_type VARCHAR(64) NOT NULL COMMENT '任务类型',
    MODIFY COLUMN source_type VARCHAR(64) NULL COMMENT '来源类型',
    MODIFY COLUMN source_code VARCHAR(128) NULL COMMENT '来源编码',
    MODIFY COLUMN title VARCHAR(256) NOT NULL COMMENT '任务标题',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '任务状态',
    MODIFY COLUMN progress_percent INT NULL COMMENT '进度百分比',
    MODIFY COLUMN collapsible TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否可折叠',
    MODIFY COLUMN background TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否后台任务',
    MODIFY COLUMN detached TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否与主对话分离展示',
    MODIFY COLUMN result_ready TINYINT(1) NOT NULL DEFAULT 0 COMMENT '结果是否可查看',
    MODIFY COLUMN latest_output_json LONGTEXT NULL COMMENT '最新输出快照',
    MODIFY COLUMN result_preview_json LONGTEXT NULL COMMENT '结果预览',
    MODIFY COLUMN action_json LONGTEXT NULL COMMENT '前端动作定义',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN completed_at DATETIME NULL COMMENT '完成时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE agent_task_event
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN event_id VARCHAR(128) NOT NULL COMMENT '事件标识',
    MODIFY COLUMN task_id VARCHAR(128) NOT NULL COMMENT '任务标识',
    MODIFY COLUMN thread_id VARCHAR(128) NULL COMMENT '线程标识',
    MODIFY COLUMN assistant_uid VARCHAR(128) NULL COMMENT '平台用户标识',
    MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '事件状态',
    MODIFY COLUMN sequence_no BIGINT NULL COMMENT '事件序号',
    MODIFY COLUMN payload_json LONGTEXT NULL COMMENT '事件载荷',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE user_inbox_notification
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN notification_id VARCHAR(128) NOT NULL COMMENT '通知标识',
    MODIFY COLUMN assistant_uid VARCHAR(128) NOT NULL COMMENT '平台用户标识',
    MODIFY COLUMN task_id VARCHAR(128) NULL COMMENT '关联任务标识',
    MODIFY COLUMN thread_id VARCHAR(128) NULL COMMENT '关联线程标识',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '通知状态',
    MODIFY COLUMN title VARCHAR(256) NOT NULL COMMENT '通知标题',
    MODIFY COLUMN body TEXT NULL COMMENT '通知正文',
    MODIFY COLUMN action_json LONGTEXT NULL COMMENT '点击动作定义',
    MODIFY COLUMN read_at DATETIME NULL COMMENT '已读时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chat_thread
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN thread_id VARCHAR(128) NOT NULL COMMENT '线程标识',
    MODIFY COLUMN assistant_uid VARCHAR(128) NOT NULL COMMENT '平台用户标识',
    MODIFY COLUMN app_name VARCHAR(128) NULL COMMENT '应用名称',
    MODIFY COLUMN system_code VARCHAR(128) NULL COMMENT '系统编码',
    MODIFY COLUMN title VARCHAR(256) NULL COMMENT '线程标题',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'UNDERSTANDING' COMMENT '线程状态',
    MODIFY COLUMN phase VARCHAR(32) NOT NULL DEFAULT 'UNDERSTANDING' COMMENT '当前阶段',
    MODIFY COLUMN unfinished TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否未完成',
    MODIFY COLUMN can_resume TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否可恢复',
    MODIFY COLUMN tool_code VARCHAR(256) NULL COMMENT '当前关联工具编码',
    MODIFY COLUMN pending_card_type VARCHAR(32) NULL COMMENT '待处理卡片类型',
    MODIFY COLUMN last_user_message TEXT NULL COMMENT '最后一条用户消息',
    MODIFY COLUMN last_assistant_message TEXT NULL COMMENT '最后一条助手消息',
    MODIFY COLUMN last_message_preview TEXT NULL COMMENT '最后一条消息摘要',
    MODIFY COLUMN last_event_type VARCHAR(64) NULL COMMENT '最后一条事件类型',
    MODIFY COLUMN last_message_at DATETIME NULL COMMENT '最后消息时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chat_message
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN message_id VARCHAR(128) NOT NULL COMMENT '消息标识',
    MODIFY COLUMN thread_id VARCHAR(128) NOT NULL COMMENT '线程标识',
    MODIFY COLUMN assistant_uid VARCHAR(128) NOT NULL COMMENT '平台用户标识',
    MODIFY COLUMN turn_id VARCHAR(128) NULL COMMENT '轮次标识',
    MODIFY COLUMN source_key VARCHAR(256) NULL COMMENT '幂等来源键',
    MODIFY COLUMN message_type VARCHAR(32) NOT NULL COMMENT '消息类型',
    MODIFY COLUMN event_type VARCHAR(64) NULL COMMENT '事件类型',
    MODIFY COLUMN stage VARCHAR(32) NULL COMMENT '所属阶段',
    MODIFY COLUMN status VARCHAR(32) NULL COMMENT '消息状态',
    MODIFY COLUMN title VARCHAR(256) NULL COMMENT '消息标题',
    MODIFY COLUMN summary_text TEXT NULL COMMENT '摘要文本',
    MODIFY COLUMN payload_json LONGTEXT NOT NULL COMMENT '结构化载荷',
    MODIFY COLUMN collapsed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认折叠',
    MODIFY COLUMN revision_no INT NOT NULL DEFAULT 1 COMMENT '修订版本号',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
