CREATE TABLE execution_trace (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trace_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    space_id BIGINT,
    agent_app_code VARCHAR(128),
    role_package_code VARCHAR(128),
    role_package_version VARCHAR(64),
    scenario_code VARCHAR(128),
    platform_principal_id VARCHAR(128),
    thread_id VARCHAR(128),
    artifact_code VARCHAR(128) NOT NULL,
    artifact_type VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    proactive TINYINT(1) NOT NULL DEFAULT 0,
    total_steps INT NOT NULL DEFAULT 0,
    completed_steps INT NOT NULL DEFAULT 0,
    duration_ms BIGINT,
    estimated_cost DOUBLE NOT NULL DEFAULT 0,
    started_at DATETIME,
    completed_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_execution_trace_run_id (run_id),
    KEY idx_execution_trace_role (space_id, agent_app_code, role_package_code, scenario_code, started_at),
    KEY idx_execution_trace_status (status, started_at)
);

CREATE TABLE execution_span (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trace_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    step_id VARCHAR(128),
    span_type VARCHAR(32) NOT NULL,
    span_name VARCHAR(256),
    status VARCHAR(32) NOT NULL,
    sequence_no BIGINT NOT NULL DEFAULT 0,
    duration_ms BIGINT,
    payload_json JSON,
    started_at DATETIME,
    completed_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_execution_span_trace (trace_id, sequence_no),
    KEY idx_execution_span_run_step (run_id, step_id)
);
