-- Seed reward-related internal tool_meta entries for the migration profile.

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES
(
    'default',
    'gougu_oa.reward_category_options',
    'Reward Category Options',
    'Query reward category options for reward and punishment workflows.',
    'gougu_oa',
    '/user/rewardscate/datalist',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_reward_categories","type":"HTTP","config":{"method":"GET","endpoint":"/user/rewardscate/datalist","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"}}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.employee_reward_punishment_create_one',
    'Create Reward Punishment Record',
    'Create one employee reward or punishment record.',
    'gougu_oa',
    '/user/rewards/add',
    'POST',
    'application/x-www-form-urlencoded',
    '{"type":"object","properties":{"rewards_cate":{"type":"string"},"types":{"type":"string"},"status":{"type":"string"},"uname":{"type":"string"},"uid":{"type":"string"},"cost":{"type":"string"},"rewards_time":{"type":"string"},"thing":{"type":"string"},"remark":{"type":"string"},"id":{"type":"string"}},"required":["rewards_cate","types","uname","uid","cost","rewards_time"]}',
    '{"version":"2.0","entry":["create"],"terminal":["create"],"steps":{"create":{"stepId":"create","name":"create_reward_record","type":"HTTP","config":{"method":"POST","endpoint":"/user/rewards/add","contentType":"application/x-www-form-urlencoded","inputMapping":{"rewards_cate":"${rewards_cate}","types":"${types}","status":"${status}","uname":"${uname}","uid":"${uid}","cost":"${cost}","rewards_time":"${rewards_time}","thing":"${thing}","remark":"${remark}","id":"${id}"},"outputMapping":{"message":"$.msg","data":"$.data"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"ACTION","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'WRITE',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
