-- Seed reward employee lookup tool_meta entry for the migration profile.

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES (
    'default',
    'gougu_oa.reward_employee_lookup',
    'Reward Employee Lookup',
    'Query employee records for reward and punishment workflows.',
    'gougu_oa',
    '/user/user/index',
    'GET',
    'application/json',
    '{"type":"object","properties":{"query":{"type":"object","properties":{"page":{"type":"integer"},"limit":{"type":"integer"},"status":{"type":"integer"},"type":{"type":"string"},"keywords":{"type":"string"},"did":{"type":"integer"}},"required":["keywords"]}}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_reward_employee","type":"HTTP","config":{"method":"GET","endpoint":"/user/user/index","contentType":"application/json","inputMapping":{"query":"${query}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
