-- 迁移环境：新增“公司车辆信息查询”tool_meta 配置，供前端“查询公司车辆信息”直接触发。

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES (
    'default',
    'gougu_oa.company_car_info_query',
    '公司车辆信息查询',
    '查询公司车辆信息列表。',
    'gougu_oa',
    '/adm/car/datalist?page=1&limit=20&keywords=',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_company_car_list","type":"HTTP","config":{"method":"GET","endpoint":"/adm/car/datalist?page=1&limit=20&keywords=","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"USER","invocationPolicy":"DIRECT","executionMode":"SYNC","keywords":["公司车辆","车辆信息","车辆列表"]}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
