-- 迁移环境：新增“车辆费用新增”相关 tool_meta，复用现有前端表单 + 后端 tool_meta 执行链路。

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES
(
    'default',
    'gougu_oa.car_fee_car_lookup',
    '车辆列表查询',
    '查询车辆列表，供车辆费用新增时根据 car_id 回填 car_name。',
    'gougu_oa',
    '/api/get_car',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_car_list","type":"HTTP","config":{"method":"GET","endpoint":"/api/get_car","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.car_fee_add',
    '新增车辆费用',
    '提交车辆费用新增记录。',
    'gougu_oa',
    '/adm/car/fee_add',
    'POST',
    'application/json',
    '{"type":"object","properties":{"car_name":{"type":"string"},"car_id":{"type":"string"},"types":{"type":"string"},"title":{"type":"string"},"fee_time":{"type":"string"},"amount":{"type":"string"},"handled_name":{"type":"string"},"handled":{"type":"string"},"file_ids":{"type":"string"},"content":{"type":"string"}},"required":["car_name","car_id","types","title","fee_time","amount","handled_name","handled"]}',
    '{"version":"2.0","entry":["create"],"terminal":["create"],"steps":{"create":{"stepId":"create","name":"create_car_fee_record","type":"HTTP","config":{"method":"POST","endpoint":"/adm/car/fee_add","contentType":"application/json","inputMapping":{"car_name":"${car_name}","car_id":"${car_id}","types":"${types}","title":"${title}","fee_time":"${fee_time}","amount":"${amount}","handled_name":"${handled_name}","handled":"${handled}","file_ids":"${file_ids}","content":"${content}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"ACTION","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'WRITE',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
