-- Seed seal-application lookup and submit tool_meta entries for the migration profile.

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES
(
    'default',
    'gougu_oa.seal_category_lookup',
    'Seal Category Lookup',
    'Query seal category options for the seal-application workflow.',
    'gougu_oa',
    '/adm/sealcate/datalist',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_seal_category_options","type":"HTTP","config":{"method":"GET","endpoint":"/adm/sealcate/datalist","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.seal_user_lookup',
    'Seal User Lookup',
    'Query candidate users for approver and copy fields in the seal-application workflow.',
    'gougu_oa',
    '/api/oa_integration/get_all_users',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_seal_users","type":"HTTP","config":{"method":"GET","endpoint":"/api/oa_integration/get_all_users","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.seal_apply_add',
    'Seal Apply Add',
    'Create a new seal-application record.',
    'gougu_oa',
    '/adm/seal/add',
    'POST',
    'application/x-www-form-urlencoded',
    '{"type":"object","properties":{"title":{"type":"string"},"did":{"type":"string"},"num":{"type":"string"},"use_time":{"type":"string"},"seal_cate_id":{"type":"string"},"is_borrow":{"type":"string"},"start_time":{"type":"string"},"end_time":{"type":"string"},"content":{"type":"string"},"file":{"type":"string"},"file_ids":{"type":"string"},"flow_id":{"type":"string"},"check_uames":{"type":"string"},"check_uids":{"type":"string"},"check_copy_unames":{"type":"string"},"check_copy_uids":{"type":"string"}},"required":["title","did","num","use_time","seal_cate_id","is_borrow","content","flow_id","check_uames","check_uids"]}',
    '{"version":"2.0","entry":["create"],"terminal":["create"],"steps":{"create":{"stepId":"create","name":"create_seal_apply","type":"HTTP","config":{"method":"POST","endpoint":"/adm/seal/add","contentType":"application/x-www-form-urlencoded","inputMapping":{"title":"${title}","did":"${did}","num":"${num}","use_time":"${use_time}","seal_cate_id":"${seal_cate_id}","is_borrow":"${is_borrow}","start_time":"${start_time}","end_time":"${end_time}","content":"${content}","file":"${file}","file_ids":"${file_ids}","flow_id":"${flow_id}","check_uames":"${check_uames}","check_uids":"${check_uids}","check_copy_unames":"${check_copy_unames}","check_copy_uids":"${check_copy_uids}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"ACTION","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'WRITE',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.seal_apply_submit',
    'Seal Apply Submit',
    'Submit seal-application approval.',
    'gougu_oa',
    '/api/check/submit_check',
    'POST',
    'application/x-www-form-urlencoded',
    '{"type":"object","properties":{"action_id":{"type":"string"},"check_name":{"type":"string"}},"required":["action_id","check_name"]}',
    '{"version":"2.0","entry":["submit"],"terminal":["submit"],"steps":{"submit":{"stepId":"submit","name":"submit_seal_apply_approval","type":"HTTP","config":{"method":"POST","endpoint":"/api/check/submit_check","contentType":"application/x-www-form-urlencoded","inputMapping":{"action_id":"${action_id}","check_name":"${check_name}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"ACTION","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'WRITE',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
