-- Seed high-intent customer query tool_meta entry for the migration profile.

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES (
    'default',
    'gougu_oa.high_intent_customer_query',
    'High Intent Customer Query',
    'Query high intent customers for a specified employee through tool_meta.',
    'gougu_oa',
    '/customer/customer/datalist',
    'GET',
    'application/json',
    '{"type":"object","properties":{"query":{"type":"object","properties":{"page":{"type":"integer","default":1},"limit":{"type":"integer","default":20},"follow_time":{"type":"string"},"next_time":{"type":"string"},"industry_id":{"type":"string"},"grade_id":{"type":"string"},"source_id":{"type":"string"},"customer_status":{"type":"string"},"intent_status":{"type":"string","default":"8"},"username":{"type":"string"},"uid":{"type":"string"},"keywords":{"type":"string"},"tab":{"type":"string","default":"0"},"order_field":{"type":"string"},"order_type":{"type":"string"}},"required":["username"]}}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_high_intent_customer","type":"HTTP","config":{"method":"GET","endpoint":"/customer/customer/datalist","contentType":"application/json","inputMapping":{"query":"${query}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
