-- Seed expense-application lookup and submit tool_meta entries for the migration profile.

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES
(
    'default',
    'gougu_oa.expense_subject_lookup',
    'Expense Subject Lookup',
    'Query expense subject options for the expense-application workflow.',
    'gougu_oa',
    '/home/cate/enterprise',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_expense_subject_options","type":"HTTP","config":{"method":"GET","endpoint":"/home/cate/enterprise","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.expense_category_lookup',
    'Expense Category Lookup',
    'Query expense category options for the expense-application workflow.',
    'gougu_oa',
    '/finance/expensecate/datalist',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_expense_category_options","type":"HTTP","config":{"method":"GET","endpoint":"/finance/expensecate/datalist","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.expense_project_lookup',
    'Expense Project Lookup',
    'Query project options for the expense-application workflow.',
    'gougu_oa',
    '/project/api/get_project',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_expense_project_options","type":"HTTP","config":{"method":"GET","endpoint":"/project/api/get_project","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.expense_user_lookup',
    'Expense User Lookup',
    'Query candidate users for applicant, approver and copy fields in the expense-application workflow.',
    'gougu_oa',
    '/api/oa_integration/get_all_users',
    'GET',
    'application/json',
    '{"type":"object","properties":{}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_expense_users","type":"HTTP","config":{"method":"GET","endpoint":"/api/oa_integration/get_all_users","contentType":"application/json","outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.expense_add',
    'Expense Add',
    'Create a new expense-application record.',
    'gougu_oa',
    '/finance/expense/add',
    'POST',
    'application/x-www-form-urlencoded',
    '{"type":"object","properties":{"body":{"type":"object"}},"required":["body"]}',
    '{"version":"2.0","entry":["create"],"terminal":["create"],"steps":{"create":{"stepId":"create","name":"create_expense_apply","type":"HTTP","config":{"method":"POST","endpoint":"/finance/expense/add","contentType":"application/x-www-form-urlencoded","inputMapping":{"body":"${body}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"ACTION","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'WRITE',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
