-- Seed invoice-application tool_meta entries for the migration profile.

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES
(
    'default',
    'gougu_oa.invoice_customer_lookup',
    'Invoice Customer Lookup',
    'Query customer options for enterprise invoice titles.',
    'gougu_oa',
    '/customer/customer/datalist',
    'GET',
    'application/json',
    '{"type":"object","properties":{"query":{"type":"object","properties":{"page":{"type":"string","default":"1"},"limit":{"type":"string","default":"20"},"keywords":{"type":"string"}}}}}',
    '{"version":"2.0","entry":["query"],"terminal":["query"],"steps":{"query":{"stepId":"query","name":"query_invoice_customers","type":"HTTP","config":{"method":"GET","endpoint":"/customer/customer/datalist","contentType":"application/json","inputMapping":{"query":"${query}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"QUERY","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'READ',
    1,
    'enabled'
),
(
    'default',
    'gougu_oa.invoice_add',
    'Invoice Add',
    'Create a new invoice-application record.',
    'gougu_oa',
    '/finance/invoice/add',
    'POST',
    'application/x-www-form-urlencoded',
    '{"type":"object","properties":{"body":{"type":"object"}},"required":["body"]}',
    '{"version":"2.0","entry":["create"],"terminal":["create"],"steps":{"create":{"stepId":"create","name":"create_invoice_apply","type":"HTTP","config":{"method":"POST","endpoint":"/finance/invoice/add","contentType":"application/x-www-form-urlencoded","inputMapping":{"body":"${body}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"ACTION","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'WRITE',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
