-- Seed invoice submit-check tool_meta for the migration profile.

INSERT INTO tool_meta (
    tenant_id,
    tool_code,
    tool_name,
    description,
    system_code,
    api_endpoint,
    http_method,
    content_type,
    parameter_schema,
    execution_plan,
    interaction_policy,
    risk_level,
    requires_auth,
    requires_confirm,
    capability_type,
    version,
    status
) VALUES (
    'default',
    'gougu_oa.invoice_submit',
    'Invoice Submit',
    'Submit an invoice-application approval request after the record is created.',
    'gougu_oa',
    '/api/check/submit_check',
    'POST',
    'application/x-www-form-urlencoded',
    '{"type":"object","properties":{"body":{"type":"object"}},"required":["body"]}',
    '{"version":"2.0","entry":["submit"],"terminal":["submit"],"steps":{"submit":{"stepId":"submit","name":"submit_invoice_approval","type":"HTTP","config":{"method":"POST","endpoint":"/api/check/submit_check","contentType":"application/x-www-form-urlencoded","inputMapping":{"body":"${body}"},"outputMapping":{"data":"$.data","message":"$.msg"},"successCondition":"$.code == 0"}}}}',
    '{"toolType":"ACTION","visibility":"INTERNAL","invocationPolicy":"DEPENDENCY_ONLY","executionMode":"SYNC","cacheScope":"REQUEST"}',
    'LOW',
    1,
    0,
    'WRITE',
    1,
    'enabled'
)
ON DUPLICATE KEY UPDATE
    tool_name = VALUES(tool_name),
    description = VALUES(description),
    system_code = VALUES(system_code),
    api_endpoint = VALUES(api_endpoint),
    http_method = VALUES(http_method),
    content_type = VALUES(content_type),
    parameter_schema = VALUES(parameter_schema),
    execution_plan = VALUES(execution_plan),
    interaction_policy = VALUES(interaction_policy),
    risk_level = VALUES(risk_level),
    requires_auth = VALUES(requires_auth),
    requires_confirm = VALUES(requires_confirm),
    capability_type = VALUES(capability_type),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
