CREATE TABLE assistant_system_registry (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    system_code          VARCHAR(64) NOT NULL UNIQUE,
    system_name          VARCHAR(128) NOT NULL,
    system_desc          TEXT,
    domain_keywords      TEXT,
    base_url             VARCHAR(512) NOT NULL,
    bind_endpoint        VARCHAR(512),
    bind_method          VARCHAR(16),
    bind_request         TEXT,
    bind_response        TEXT,
    token_endpoint       VARCHAR(512),
    token_method         VARCHAR(16),
    token_request        TEXT,
    token_response       TEXT,
    token_ttl            INT DEFAULT 7200,
    token_header_name    VARCHAR(64) DEFAULT 'Authorization',
    token_header_prefix  VARCHAR(64) DEFAULT 'Bearer ',
    status               VARCHAR(16) NOT NULL DEFAULT 'active',
    priority             INT DEFAULT 0,
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE assistant_capability_registry (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    system_id            BIGINT,
    system_code          VARCHAR(64) NOT NULL,
    capability_code      VARCHAR(128) NOT NULL,
    capability_name      VARCHAR(256) NOT NULL,
    capability_desc      TEXT,
    intent_keywords      TEXT,
    intent_examples      TEXT,
    api_endpoint         VARCHAR(512),
    http_method          VARCHAR(16),
    content_type         VARCHAR(128),
    request_schema       LONGTEXT,
    response_config      LONGTEXT,
    requires_auth        TINYINT NOT NULL DEFAULT 1,
    status               VARCHAR(16) NOT NULL DEFAULT 'enabled',
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    capability_type      VARCHAR(16) NOT NULL DEFAULT 'ACTION',
    side_effect          VARCHAR(32) DEFAULT 'NONE',
    capability_mode      VARCHAR(16) DEFAULT 'SIMPLE',
    slot_schema          LONGTEXT,
    behavior_strategy    LONGTEXT,
    flow_steps           LONGTEXT,
    version              INT NOT NULL DEFAULT 1,
    tenant_id            VARCHAR(64) NOT NULL DEFAULT 'default',
    UNIQUE KEY uk_system_capability_version_tenant (system_code, capability_code, version, tenant_id)
);

