-- Legacy Gougu OA registry seed data for migration profile.
-- Source: previously running assistant system definitions.

INSERT INTO `assistant_system_registry` (
  `system_code`, `system_name`, `system_desc`, `domain_keywords`, `base_url`,
  `bind_endpoint`, `bind_method`, `bind_request`, `bind_response`,
  `token_endpoint`, `token_method`, `token_request`, `token_response`,
  `token_ttl`, `token_header_name`, `token_header_prefix`, `status`, `priority`,
  `created_at`, `updated_at`
) VALUES (
  'gougu_oa',
  '勾股OA办公系统',
  '企业内部办公自动化系统，支持请假、考勤、审批、会议、报销、汇报等办公功能',
  '["请假", "考勤", "审批", "会议", "报销", "周报", "打卡"]',
  'http://office.ai.devefive.com',
  '/api/oa_integration/bind_user',
  'POST',
  '{"password": "${password}", "username": "${username}"}',
  '{"user_id_field": "data.user_id", "username_field": "data.username", "display_name_field": "data.name"}',
  '/api/oa_integration/get_token',
  'POST',
  '{"system_user_id": "${system_user_id}"}',
  '{"token_field": "data.token", "expire_field": "data.expire_at"}',
  7200,
  'Authorization',
  'Bearer ',
  'active',
  10,
  '2026-01-23 15:45:44',
  '2026-02-09 15:54:54'
)
ON DUPLICATE KEY UPDATE
  `system_name` = VALUES(`system_name`),
  `system_desc` = VALUES(`system_desc`),
  `domain_keywords` = VALUES(`domain_keywords`),
  `base_url` = VALUES(`base_url`),
  `bind_endpoint` = VALUES(`bind_endpoint`),
  `bind_method` = VALUES(`bind_method`),
  `bind_request` = VALUES(`bind_request`),
  `bind_response` = VALUES(`bind_response`),
  `token_endpoint` = VALUES(`token_endpoint`),
  `token_method` = VALUES(`token_method`),
  `token_request` = VALUES(`token_request`),
  `token_response` = VALUES(`token_response`),
  `token_ttl` = VALUES(`token_ttl`),
  `token_header_name` = VALUES(`token_header_name`),
  `token_header_prefix` = VALUES(`token_header_prefix`),
  `status` = VALUES(`status`),
  `priority` = VALUES(`priority`),
  `updated_at` = VALUES(`updated_at`);

INSERT INTO `system_access_profile` (
  `system_code`, `base_url`, `token_endpoint`, `token_method`,
  `token_request_tpl`, `token_response_path`,
  `token_header_name`, `token_header_prefix`, `token_ttl_seconds`, `status`
) VALUES (
  'gougu_oa',
  'http://office.ai.devefive.com',
  '/api/oa_integration/get_token',
  'POST',
  '{"system_user_id": "${system_user_id}"}',
  'data.token',
  'Authorization',
  'Bearer ',
  7200,
  'enabled'
)
ON DUPLICATE KEY UPDATE
  `base_url` = VALUES(`base_url`),
  `token_endpoint` = VALUES(`token_endpoint`),
  `token_method` = VALUES(`token_method`),
  `token_request_tpl` = VALUES(`token_request_tpl`),
  `token_response_path` = VALUES(`token_response_path`),
  `token_header_name` = VALUES(`token_header_name`),
  `token_header_prefix` = VALUES(`token_header_prefix`),
  `token_ttl_seconds` = VALUES(`token_ttl_seconds`),
  `status` = VALUES(`status`);

INSERT INTO `assistant_capability_registry` (
  `system_id`, `system_code`, `capability_code`, `capability_name`, `capability_desc`,
  `intent_keywords`, `intent_examples`, `api_endpoint`, `http_method`, `content_type`,
  `request_schema`, `response_config`, `requires_auth`, `status`, `created_at`, `updated_at`,
  `capability_type`, `side_effect`, `capability_mode`, `slot_schema`, `behavior_strategy`, `flow_steps`
) VALUES (
  (SELECT `id` FROM `assistant_system_registry` WHERE `system_code` = 'gougu_oa' LIMIT 1),
  'gougu_oa',
  'leave_application',
  '请假审批',
  '提交请假申请，支持事假、年假、调休假、病假、婚假、丧假、产假、陪产假等多种类型',
  '["请假", "休假", "事假", "年假", "病假", "婚假", "产假", "调休"]',
  '["我想请假", "帮我请三天年假", "明天请一天事假", "我要请病假", "申请产假"]',
  '/home/leaves/add',
  'POST',
  'application/x-www-form-urlencoded',
  '{"type": "object", "required": ["types", "start_date", "end_date", "reason"], "properties": {"types": {"type": "integer", "title": "请假类型", "description": "1=事假, 2=年假, 3=调休假, 4=病假, 5=婚假, 6=丧假, 7=产假, 8=陪产假, 9=其他"}, "reason": {"type": "string", "title": "请假原因", "description": "详细的请假原因"}, "duration": {"type": "number", "title": "请假时长", "description": "请假天数（工作日）"}, "end_date": {"type": "string", "title": "结束日期", "description": "请假结束日期，格式：YYYY-MM-DD"}, "check_uids": {"type": "string", "title": "审批人ID"}, "start_date": {"type": "string", "title": "开始日期", "description": "请假开始日期，格式：YYYY-MM-DD"}, "check_flow_id": {"type": "integer", "title": "审批流程ID"}, "check_copy_uids": {"type": "string", "title": "抄送人ID"}}}',
  '{"next_step": {"method": "POST", "extract": {"check_id": "data.id"}, "endpoint": "/api/check/submit_check"}}',
  1,
  'enabled',
  '2026-01-23 15:54:51',
  '2026-01-31 18:29:54',
  'ACTION',
  'NONE',
  'FLOW',
  '{"slots": [{"name": "types", "type": "integer", "title": "请假类型", "aiHint": "请假类型，从系统获取可用的请假类型列表。必须用户输入中提取或从请假原因推断。", "askMode": "BATCH", "options": {"source": "API", "apiConfig": {"method": "GET", "endpoint": "/api/oa_integration/get_leave_types", "labelField": "name", "valueField": "id"}, "enumMapping": {"丧假": 6, "事假": 1, "产假": 7, "其他": 9, "婚假": 5, "年假": 2, "病假": 4, "调休": 3, "调休假": 3, "陪产假": 8}}, "priority": "CORE", "required": true, "uiComponent": "select", "inferredFrom": ["reason"], "displayConfig": {"summaryIcon": "🏷", "summaryGroup": "CORE", "summaryOrder": 1, "showInSummary": true}}, {"name": "start_date", "type": "string", "title": "开始日期", "aiHint": "请假开始日期，格式：YYYY-MM-DD，如 2026-01-27", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "date", "displayConfig": {"summaryIcon": "📅", "summaryGroup": "CORE", "summaryOrder": 2, "showInSummary": true}}, {"name": "end_date", "type": "string", "title": "结束日期", "aiHint": "请假结束日期，格式：YYYY-MM-DD，必须大于或等于开始日期", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "date", "displayConfig": {"summaryIcon": "📅", "summaryGroup": "CORE", "summaryOrder": 3, "showInSummary": true}}, {"name": "reason", "type": "string", "title": "请假原因", "aiHint": "详细的请假原因。注意：请假原因可用于智能推断请假类型（types字段）", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "textarea", "displayConfig": {"summaryIcon": "📝", "summaryGroup": "SECONDARY", "summaryOrder": 5, "showInSummary": true}}, {"name": "duration", "type": "number", "title": "请假时长（天数）", "aiHint": "请假天数，系统会根据开始日期和结束日期自动计算", "askMode": "AUTO", "computed": {"type": "FUNCTION", "params": {"end": "end_date", "unit": "days", "start": "start_date", "include_end": true, "include_start": true}, "enabled": true, "function": "date_diff", "defaultValue": 1}, "priority": "OPTIONAL", "required": false, "uiComponent": "number", "displayConfig": {"summaryIcon": "", "summaryGroup": "CORE", "summaryOrder": 4, "displaySuffix": "天", "showInSummary": true}}, {"name": "check_flow_id", "type": "integer", "title": "审批流程", "aiHint": "审批流程，系统会自动获取可用的审批流程列表，并默认选择第一个", "askMode": "AUTO", "options": {"source": "API", "apiConfig": {"method": "GET", "params": {"flow_id": "0", "action_id": "0", "check_name": "leaves"}, "endpoint": "/api/check/get_flow_nodes", "labelField": "title", "valueField": "flow_id"}, "autoSelect": {"when": "always", "enabled": true, "strategy": "first"}}, "priority": "OPTIONAL", "required": false, "uiComponent": "select", "displayConfig": {"showInSummary": false}}, {"name": "check_copy_uids", "type": "array", "title": "抄送人", "aiHint": "抄送人（可选），不主动询问", "askMode": "AUTO", "options": {"source": "API", "multiple": true, "apiConfig": {"endpoint": "/api/oa_integration/get_all_users", "labelField": "name", "valueField": "id"}, "autoSelect": {"enabled": false}}, "priority": "SUPPLEMENTARY", "required": false, "uiComponent": "select", "displayConfig": {"displayType": "avatar-list", "summaryIcon": "📧", "summaryGroup": "SECONDARY", "summaryOrder": 7, "showInSummary": true}}, {"name": "check_uids", "type": "string", "title": "审批人", "aiHint": "审批人，不主动询问", "askMode": "AUTO", "options": {"source": "API", "multiple": true, "apiConfig": {"endpoint": "/api/oa_integration/get_all_users", "labelField": "name", "valueField": "id"}, "autoSelect": {"when": "always", "enabled": true, "strategy": "first"}}, "priority": "SUPPLEMENTARY", "required": false, "uiComponent": "select", "displayConfig": {"displayType": "avatar", "summaryIcon": "👤", "summaryGroup": "SECONDARY", "summaryOrder": 6, "showInSummary": true}}]}',
  '{"collect": {"batch_size": 4, "max_rounds": 5, "collect_order": "priority_first", "skip_collected": true}, "confirm": {"enabled": true, "allow_edit": true, "show_all_params": true, "confirmation_prompt": "请确认以下请假信息，如需修改请直接说明。确认无误请回复【确认】或【提交】"}, "execute": {"max_retries": 0, "auto_execute": false, "retry_on_fail": false}}',
  '{"entry": ["create_leave"], "steps": {"create_leave": {"name": "创建请假记录", "next": ["submit_approval"], "type": "HTTP", "config": {"method": "POST", "endpoint": "/home/leaves/add", "contentType": "application/x-www-form-urlencoded", "inputMapping": {"id": "0", "types": "${types}", "reason": "${reason}", "duration": "${duration}", "end_date": "${end_date}", "file_ids": "", "start_date": "${start_date}"}, "outputMapping": {"message": "$.msg", "leave_id": "$.data.return_id"}, "successCondition": "$.code == 0"}, "stepId": "create_leave"}, "submit_approval": {"name": "提交审批", "type": "HTTP", "config": {"method": "POST", "endpoint": "/api/check/submit_check", "contentType": "application/x-www-form-urlencoded", "inputMapping": {"flow_id": "${check_flow_id}", "action_id": "${create_leave.leave_id}", "check_name": "leaves", "check_uids": "${check_uids}", "check_copy_uids": "${check_copy_uids}"}, "outputMapping": {"code": "$.code", "final_message": "$.msg"}, "successCondition": "$.code == 0"}, "stepId": "submit_approval", "dependsOn": ["create_leave"]}}, "version": "2.0", "terminal": ["submit_approval"]}'
)
ON DUPLICATE KEY UPDATE
  `system_id` = VALUES(`system_id`),
  `capability_name` = VALUES(`capability_name`),
  `capability_desc` = VALUES(`capability_desc`),
  `intent_keywords` = VALUES(`intent_keywords`),
  `intent_examples` = VALUES(`intent_examples`),
  `api_endpoint` = VALUES(`api_endpoint`),
  `http_method` = VALUES(`http_method`),
  `content_type` = VALUES(`content_type`),
  `request_schema` = VALUES(`request_schema`),
  `response_config` = VALUES(`response_config`),
  `requires_auth` = VALUES(`requires_auth`),
  `status` = VALUES(`status`),
  `capability_type` = VALUES(`capability_type`),
  `side_effect` = VALUES(`side_effect`),
  `capability_mode` = VALUES(`capability_mode`),
  `slot_schema` = VALUES(`slot_schema`),
  `behavior_strategy` = VALUES(`behavior_strategy`),
  `flow_steps` = VALUES(`flow_steps`),
  `updated_at` = VALUES(`updated_at`);

INSERT INTO `assistant_capability_registry` (
  `system_id`, `system_code`, `capability_code`, `capability_name`, `capability_desc`,
  `intent_keywords`, `intent_examples`, `api_endpoint`, `http_method`, `content_type`,
  `request_schema`, `response_config`, `requires_auth`, `status`, `created_at`, `updated_at`,
  `capability_type`, `side_effect`, `capability_mode`, `slot_schema`, `behavior_strategy`, `flow_steps`
) VALUES (
  (SELECT `id` FROM `assistant_system_registry` WHERE `system_code` = 'gougu_oa' LIMIT 1),
  'gougu_oa',
  'meeting_room_booking',
  '会议室预定',
  '预定会议室并提交审批，支持选择会议室、设置会议时间、添加参会人员等',
  '["预定会议室", "会议室预定", "订会议室", "预约会议室", "开会", "会议", "会议室"]',
  '["我要预定会议室", "明天下午2点订个会议室", "帮我预约明天的会议室", "需要订个会议室开会"]',
  '/adm/meeting/add',
  'POST',
  'application/x-www-form-urlencoded',
  '{"type": "object", "required": ["room_id", "title", "start_date", "end_date", "num"], "properties": {"num": {"type": "integer", "title": "会议人数", "description": "参加会议的人数"}, "title": {"type": "string", "title": "会议主题", "description": "会议的主题或标题"}, "remark": {"type": "string", "title": "会议说明", "description": "会议的详细说明或备注"}, "room_id": {"type": "integer", "title": "会议室", "description": "要预定的会议室ID"}, "end_date": {"type": "string", "title": "结束时间", "description": "会议结束时间，格式：YYYY-MM-DD HH:mm"}, "join_uids": {"type": "string", "title": "参会人员", "description": "参会人员ID，多个用逗号分隔"}, "check_uids": {"type": "string", "title": "审批人ID"}, "start_date": {"type": "string", "title": "开始时间", "description": "会议开始时间，格式：YYYY-MM-DD HH:mm"}, "requirement": {"type": "array", "title": "会议需求", "description": "会议需求项目ID列表"}, "check_flow_id": {"type": "integer", "title": "审批流程ID"}}}',
  '{"next_step": {"method": "POST", "extract": {"check_id": "data.id"}, "endpoint": "/api/check/submit_check"}}',
  1,
  'enabled',
  '2026-01-29 18:37:49',
  '2026-02-10 10:34:54',
  'ACTION',
  'NONE',
  'FLOW',
  '{"slots": [{"name": "room_id", "type": "integer", "title": "会议室", "aiHint": "选择要预定的会议室，从系统获取可用的会议室列表", "askMode": "BATCH", "options": {"source": "API", "apiConfig": {"method": "GET", "endpoint": "/api/oa_integration/get_meeting_rooms", "labelField": "name", "valueField": "id"}}, "priority": "CORE", "required": true, "uiComponent": "select", "displayConfig": {"summaryIcon": "🏢", "summaryGroup": "CORE", "summaryOrder": 1, "showInSummary": true}}, {"name": "title", "type": "string", "title": "会议主题", "aiHint": "会议的主题或标题，简明扼要地描述会议内容", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "text", "displayConfig": {"summaryIcon": "📌", "summaryGroup": "CORE", "summaryOrder": 2, "showInSummary": true}}, {"name": "start_date", "type": "string", "title": "开始时间", "aiHint": "会议开始时间，格式：YYYY-MM-DD HH:mm，如 2026-01-30 14:00", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "datetime", "displayConfig": {"summaryIcon": "🕐", "summaryGroup": "CORE", "summaryOrder": 3, "showInSummary": true}}, {"name": "end_date", "type": "string", "title": "结束时间", "aiHint": "会议结束时间，格式：YYYY-MM-DD HH:mm，必须大于开始时间", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "datetime", "displayConfig": {"summaryIcon": "🕐", "summaryGroup": "CORE", "summaryOrder": 4, "showInSummary": true}}, {"name": "num", "type": "integer", "title": "会议人数", "aiHint": "参加会议的人数", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "number", "displayConfig": {"summaryIcon": "👥", "summaryGroup": "CORE", "summaryOrder": 5, "showInSummary": true}}, {"name": "requirement", "type": "array", "title": "会议需求", "aiHint": "会议需求，如电子屏、投影背景、电脑等，从系统获取可用的需求列表", "askMode": "BATCH", "options": {"source": "API", "multiple": true, "apiConfig": {"method": "GET", "endpoint": "/api/oa_integration/get_meeting_requirements", "labelField": "name", "valueField": "id"}}, "priority": "CORE", "required": true, "uiComponent": "checkbox", "displayConfig": {"summaryIcon": "📋", "summaryGroup": "CORE", "summaryOrder": 6, "showInSummary": true}}, {"name": "join_uids", "type": "array", "title": "参会人员", "aiHint": "参会人员（可选），可以从部门用户中选择", "askMode": "AUTO", "options": {"source": "API", "multiple": true, "apiConfig": {"method": "GET", "endpoint": "/api/oa_integration/get_all_users", "labelField": "name", "valueField": "id"}}, "priority": "SUPPLEMENTARY", "required": false, "uiComponent": "select", "displayConfig": {"displayType": "avatar-list", "summaryIcon": "👥", "summaryGroup": "SECONDARY", "summaryOrder": 5, "showInSummary": true}}, {"name": "remark", "type": "string", "title": "会议说明", "aiHint": "会议的详细说明或备注（可选）", "askMode": "AUTO", "priority": "OPTIONAL", "required": false, "uiComponent": "textarea", "displayConfig": {"showInSummary": false}}, {"name": "check_flow_id", "type": "integer", "title": "审批流程", "aiHint": "审批流程，系统会自动获取可用的审批流程列表，并默认选择第一个", "askMode": "AUTO", "options": {"source": "API", "apiConfig": {"method": "GET", "params": {"flow_id": "0", "action_id": "0", "check_name": "meeting_order"}, "endpoint": "/api/check/get_flow_nodes", "labelField": "title", "valueField": "flow_id"}, "autoSelect": {"when": "always", "enabled": true, "strategy": "first"}}, "priority": "OPTIONAL", "required": false, "uiComponent": "select", "displayConfig": {"showInSummary": false}}, {"name": "check_uids", "type": "string", "title": "审批人", "aiHint": "审批人，系统会自动查询用户的上级领导作为默认审批人", "askMode": "AUTO", "options": {"source": "API", "apiConfig": {"method": "GET", "endpoint": "/api/oa_integration/get_department_users_tree", "labelField": "name", "valueField": "id"}, "autoSelect": {"when": "always", "enabled": true, "strategy": "first"}}, "priority": "OPTIONAL", "required": false, "uiComponent": "select", "displayConfig": {"displayType": "avatar", "summaryIcon": "👤", "summaryGroup": "SECONDARY", "summaryOrder": 6, "showInSummary": true}}]}',
  '{"collect": {"batch_size": 4, "max_rounds": 5, "collect_order": "priority_first", "skip_collected": true}, "confirm": {"enabled": true, "allow_edit": true, "show_all_params": true, "confirmation_prompt": "请确认以下会议室预定信息，如需修改请直接说明。确认无误请回复【确认】或【提交】"}, "execute": {"max_retries": 0, "auto_execute": false, "retry_on_fail": false}}',
  '{"entry": ["create_booking"], "steps": {"create_booking": {"name": "创建会议室预定记录", "next": ["submit_approval"], "type": "HTTP", "config": {"method": "POST", "endpoint": "/adm/meeting/add", "contentType": "application/x-www-form-urlencoded", "inputMapping": {"id": "0", "num": "${num}", "title": "${title}", "remark": "${remark}", "room_id": "${room_id}", "end_date": "${end_date}", "join_uids": "${join_uids}", "start_date": "${start_date}", "requirement": "${requirement}"}, "outputMapping": {"message": "$.msg", "booking_id": "$.data.return_id"}, "successCondition": "$.code == 0"}, "stepId": "create_booking"}, "submit_approval": {"name": "提交审批", "type": "HTTP", "config": {"method": "POST", "endpoint": "/api/check/submit_check", "contentType": "application/x-www-form-urlencoded", "inputMapping": {"flow_id": "${check_flow_id}", "action_id": "${create_booking.booking_id}", "check_name": "meeting_order", "check_uids": "${check_uids}", "check_copy_uids": ""}, "outputMapping": {"code": "$.code", "final_message": "$.msg"}, "successCondition": "$.code == 0"}, "stepId": "submit_approval", "dependsOn": ["create_booking"]}}, "version": "2.0", "terminal": ["submit_approval"]}'
)
ON DUPLICATE KEY UPDATE
  `system_id` = VALUES(`system_id`),
  `capability_name` = VALUES(`capability_name`),
  `capability_desc` = VALUES(`capability_desc`),
  `intent_keywords` = VALUES(`intent_keywords`),
  `intent_examples` = VALUES(`intent_examples`),
  `api_endpoint` = VALUES(`api_endpoint`),
  `http_method` = VALUES(`http_method`),
  `content_type` = VALUES(`content_type`),
  `request_schema` = VALUES(`request_schema`),
  `response_config` = VALUES(`response_config`),
  `requires_auth` = VALUES(`requires_auth`),
  `status` = VALUES(`status`),
  `capability_type` = VALUES(`capability_type`),
  `side_effect` = VALUES(`side_effect`),
  `capability_mode` = VALUES(`capability_mode`),
  `slot_schema` = VALUES(`slot_schema`),
  `behavior_strategy` = VALUES(`behavior_strategy`),
  `flow_steps` = VALUES(`flow_steps`),
  `updated_at` = VALUES(`updated_at`);

INSERT INTO `assistant_capability_registry` (
  `system_id`, `system_code`, `capability_code`, `capability_name`, `capability_desc`,
  `intent_keywords`, `intent_examples`, `api_endpoint`, `http_method`, `content_type`,
  `request_schema`, `response_config`, `requires_auth`, `status`, `created_at`, `updated_at`,
  `capability_type`, `side_effect`, `capability_mode`, `slot_schema`, `behavior_strategy`, `flow_steps`
) VALUES (
  (SELECT `id` FROM `assistant_system_registry` WHERE `system_code` = 'gougu_oa' LIMIT 1),
  'gougu_oa',
  'work_report',
  '工作周报',
  '提交工作日报、周报或月报，记录本周/本月的工作内容和下周/下月的工作计划',
  '["周报", "日报", "月报", "工作汇报", "汇报", "工作总结"]',
  '["我要写周报", "帮我提交本周工作汇报", "写一份工作日报", "提交本月工作总结"]',
  '/oa/work/add',
  'POST',
  'application/x-www-form-urlencoded',
  '{"type": "object", "required": ["types", "works", "to_uids"], "properties": {"send": {"type": "integer", "title": "是否立即发送"}, "plans": {"type": "string", "title": "下期工作计划"}, "types": {"type": "integer", "title": "汇报类型"}, "works": {"type": "string", "title": "本期工作内容"}, "remark": {"type": "string", "title": "其他事项"}, "to_uids": {"type": "string", "title": "接收人ID"}, "end_date": {"type": "string", "title": "结束日期"}, "start_date": {"type": "string", "title": "开始日期"}}}',
  '{"data_path": "data", "message_path": "msg", "field_mapping": {"report_id": "data.id"}, "success_condition": "code == 0"}',
  1,
  'enabled',
  '2026-01-28 19:00:00',
  '2026-01-31 21:46:57',
  'ACTION',
  'NONE',
  'FLOW',
  '{"slots": [{"name": "types", "type": "integer", "title": "汇报类型", "aiHint": "汇报类型：1=日报, 2=周报, 3=月报。根据用户输入自动识别，默认为周报。", "askMode": "BATCH", "options": {"source": "ENUM", "enumMapping": {"周报": 2, "日报": 1, "月报": 3}}, "priority": "CORE", "required": true, "uiComponent": "select", "defaultValue": 2, "inferredFrom": [], "displayConfig": {"summaryIcon": "📋", "summaryGroup": "CORE", "summaryOrder": 1, "showInSummary": true}}, {"name": "start_date", "type": "string", "title": "开始日期", "aiHint": "汇报的开始日期，格式：YYYY-MM-DD。根据 types 和当前日期自动推断。", "askMode": "AUTO", "priority": "OPTIONAL", "required": false, "uiComponent": "date", "inferredFrom": ["types"], "displayConfig": {"summaryIcon": "📅", "summaryGroup": "CORE", "summaryOrder": 2, "showInSummary": true}}, {"name": "end_date", "type": "string", "title": "结束日期", "aiHint": "汇报的结束日期，格式：YYYY-MM-DD。根据 types 和当前日期自动推断。", "askMode": "AUTO", "priority": "OPTIONAL", "required": false, "uiComponent": "date", "inferredFrom": ["types"], "displayConfig": {"summaryIcon": "📅", "summaryGroup": "CORE", "summaryOrder": 3, "showInSummary": true}}, {"name": "range_date", "type": "string", "title": "汇报日期范围", "aiHint": "汇报日期范围，系统根据开始日期和结束日期自动计算，格式：YYYY-MM-DD ~ YYYY-MM-DD", "askMode": "NEVER", "computed": {"type": "FUNCTION", "params": {"fields": ["start_date", " ~ ", "end_date"]}, "enabled": true, "function": "concat"}, "priority": "OPTIONAL", "required": false, "uiComponent": "text", "displayConfig": {"showInSummary": false}}, {"name": "works", "type": "string", "title": "本期工作内容", "aiHint": "已完成的工作内容。用户回答后直接接受，不要要求用户提供更多细节。用户说完成了什么就记录什么。", "askMode": "BATCH", "priority": "CORE", "required": true, "uiComponent": "textarea", "inferredFrom": [], "displayConfig": {"summaryIcon": "📝", "summaryGroup": "SECONDARY", "summaryOrder": 4, "showInSummary": true}}, {"name": "plans", "type": "string", "title": "下期工作计划", "aiHint": "下周/下月的工作计划，可选参数。系统会询问用户是否有下期计划。", "askMode": "AUTO", "priority": "SUPPLEMENTARY", "required": false, "uiComponent": "textarea", "inferredFrom": [], "displayConfig": {"showInSummary": false}}, {"name": "remark", "type": "string", "title": "其他事项", "aiHint": "其他需要说明的事项、遇到的问题或需要的协助，可选参数。", "askMode": "AUTO", "priority": "SUPPLEMENTARY", "required": false, "uiComponent": "textarea", "inferredFrom": [], "displayConfig": {"showInSummary": false}}, {"name": "send", "type": "integer", "title": "发送方式", "aiHint": "发送方式：0=仅保存，1=保存并发送。用户如果没有明确说明，默认为仅保存（0）", "askMode": "FORM_ONLY", "options": {"source": "ENUM", "enumMapping": {"仅保存": 0, "保存并发送": 1}}, "priority": "OPTIONAL", "required": false, "description": "提交后的处理方式：仅保存或保存并发送通知", "uiComponent": "radio", "defaultValue": 0, "inferredFrom": [], "displayConfig": {"showInSummary": false}}, {"name": "to_uids", "type": "string", "title": "接收人", "aiHint": "接收人，可以从部门用户中选择", "askMode": "AUTO", "options": {"source": "API", "multiple": true, "apiConfig": {"method": "GET", "endpoint": "/api/oa_integration/get_all_users", "labelField": "name", "valueField": "id"}, "autoSelect": {"when": "always", "enabled": true, "strategy": "first"}}, "priority": "SUPPLEMENTARY", "required": false, "uiComponent": "select", "displayConfig": {"displayType": "avatar-list", "summaryIcon": "👤", "summaryGroup": "SECONDARY", "summaryOrder": 5, "showInSummary": true}}]}',
  '{"collect": {"batch_size": 3, "max_rounds": 5, "collect_order": "priority_first", "skip_collected": true}, "confirm": {"enabled": true, "allow_edit": true, "show_all_params": true, "confirmation_prompt": "请确认以下工作汇报信息，如需修改请直接说明。确认无误请回复【确认】或【提交】"}, "execute": {"max_retries": 0, "auto_execute": false, "retry_on_fail": false}}',
  '{"entry": ["create_and_send_report"], "steps": {"create_and_send_report": {"name": "创建并发送工作汇报", "type": "HTTP", "config": {"method": "POST", "endpoint": "/oa/work/add", "contentType": "application/x-www-form-urlencoded", "inputMapping": {"id": "0", "file": "", "send": "${send}", "plans": "${plans}", "types": "${types}", "works": "${works}", "remark": "${remark}", "to_uids": "${to_uids}", "file_ids": "", "range_date": "${range_date}", "start_date": "${start_date}", "end_date": "${end_date}"}, "outputMapping": {"message": "$.msg", "report_id": "$.data.id"}, "successCondition": "$.code == 0"}, "stepId": "create_and_send_report"}}, "version": "2.0", "terminal": ["create_and_send_report"]}'
)
ON DUPLICATE KEY UPDATE
  `system_id` = VALUES(`system_id`),
  `capability_name` = VALUES(`capability_name`),
  `capability_desc` = VALUES(`capability_desc`),
  `intent_keywords` = VALUES(`intent_keywords`),
  `intent_examples` = VALUES(`intent_examples`),
  `api_endpoint` = VALUES(`api_endpoint`),
  `http_method` = VALUES(`http_method`),
  `content_type` = VALUES(`content_type`),
  `request_schema` = VALUES(`request_schema`),
  `response_config` = VALUES(`response_config`),
  `requires_auth` = VALUES(`requires_auth`),
  `status` = VALUES(`status`),
  `capability_type` = VALUES(`capability_type`),
  `side_effect` = VALUES(`side_effect`),
  `capability_mode` = VALUES(`capability_mode`),
  `slot_schema` = VALUES(`slot_schema`),
  `behavior_strategy` = VALUES(`behavior_strategy`),
  `flow_steps` = VALUES(`flow_steps`),
  `updated_at` = VALUES(`updated_at`);

